/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface AppFavoritesPage {
    'name': string;
  }
  interface AppHomePage {
    'jobs': any;
  }
  interface AppRoot {}
}

declare global {


  interface HTMLAppFavoritesPageElement extends Components.AppFavoritesPage, HTMLStencilElement {}
  var HTMLAppFavoritesPageElement: {
    prototype: HTMLAppFavoritesPageElement;
    new (): HTMLAppFavoritesPageElement;
  };

  interface HTMLAppHomePageElement extends Components.AppHomePage, HTMLStencilElement {}
  var HTMLAppHomePageElement: {
    prototype: HTMLAppHomePageElement;
    new (): HTMLAppHomePageElement;
  };

  interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {}
  var HTMLAppRootElement: {
    prototype: HTMLAppRootElement;
    new (): HTMLAppRootElement;
  };
  interface HTMLElementTagNameMap {
    'app-favorites-page': HTMLAppFavoritesPageElement;
    'app-home-page': HTMLAppHomePageElement;
    'app-root': HTMLAppRootElement;
  }
}

declare namespace LocalJSX {
  interface AppFavoritesPage {
    'name'?: string;
  }
  interface AppHomePage {
    'jobs'?: any;
  }
  interface AppRoot {}

  interface IntrinsicElements {
    'app-favorites-page': AppFavoritesPage;
    'app-home-page': AppHomePage;
    'app-root': AppRoot;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'app-favorites-page': LocalJSX.AppFavoritesPage & JSXBase.HTMLAttributes<HTMLAppFavoritesPageElement>;
      'app-home-page': LocalJSX.AppHomePage & JSXBase.HTMLAttributes<HTMLAppHomePageElement>;
      'app-root': LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
    }
  }
}


