/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface AppFavoritesPage {
    'name': string;
  }
  interface AppHomePage {
    'jobs': any;
  }
  interface AppJobCard {
    'jobs': any;
    'name': string;
  }
  interface AppJobItem {
    'job': any;
  }
  interface AppJobsList {
    'jobs': any;
  }
  interface AppRoot {}
}

declare global {


  interface HTMLAppFavoritesPageElement extends Components.AppFavoritesPage, HTMLStencilElement {}
  var HTMLAppFavoritesPageElement: {
    prototype: HTMLAppFavoritesPageElement;
    new (): HTMLAppFavoritesPageElement;
  };

  interface HTMLAppHomePageElement extends Components.AppHomePage, HTMLStencilElement {}
  var HTMLAppHomePageElement: {
    prototype: HTMLAppHomePageElement;
    new (): HTMLAppHomePageElement;
  };

  interface HTMLAppJobCardElement extends Components.AppJobCard, HTMLStencilElement {}
  var HTMLAppJobCardElement: {
    prototype: HTMLAppJobCardElement;
    new (): HTMLAppJobCardElement;
  };

  interface HTMLAppJobItemElement extends Components.AppJobItem, HTMLStencilElement {}
  var HTMLAppJobItemElement: {
    prototype: HTMLAppJobItemElement;
    new (): HTMLAppJobItemElement;
  };

  interface HTMLAppJobsListElement extends Components.AppJobsList, HTMLStencilElement {}
  var HTMLAppJobsListElement: {
    prototype: HTMLAppJobsListElement;
    new (): HTMLAppJobsListElement;
  };

  interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {}
  var HTMLAppRootElement: {
    prototype: HTMLAppRootElement;
    new (): HTMLAppRootElement;
  };
  interface HTMLElementTagNameMap {
    'app-favorites-page': HTMLAppFavoritesPageElement;
    'app-home-page': HTMLAppHomePageElement;
    'app-job-card': HTMLAppJobCardElement;
    'app-job-item': HTMLAppJobItemElement;
    'app-jobs-list': HTMLAppJobsListElement;
    'app-root': HTMLAppRootElement;
  }
}

declare namespace LocalJSX {
  interface AppFavoritesPage {
    'name'?: string;
  }
  interface AppHomePage {
    'jobs'?: any;
  }
  interface AppJobCard {
    'jobs'?: any;
    'name'?: string;
  }
  interface AppJobItem {
    'job'?: any;
  }
  interface AppJobsList {
    'jobs'?: any;
  }
  interface AppRoot {}

  interface IntrinsicElements {
    'app-favorites-page': AppFavoritesPage;
    'app-home-page': AppHomePage;
    'app-job-card': AppJobCard;
    'app-job-item': AppJobItem;
    'app-jobs-list': AppJobsList;
    'app-root': AppRoot;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'app-favorites-page': LocalJSX.AppFavoritesPage & JSXBase.HTMLAttributes<HTMLAppFavoritesPageElement>;
      'app-home-page': LocalJSX.AppHomePage & JSXBase.HTMLAttributes<HTMLAppHomePageElement>;
      'app-job-card': LocalJSX.AppJobCard & JSXBase.HTMLAttributes<HTMLAppJobCardElement>;
      'app-job-item': LocalJSX.AppJobItem & JSXBase.HTMLAttributes<HTMLAppJobItemElement>;
      'app-jobs-list': LocalJSX.AppJobsList & JSXBase.HTMLAttributes<HTMLAppJobsListElement>;
      'app-root': LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
    }
  }
}


